### PR TITLE
Introduce module to get inverse dependencies of a resolution request

### PR DESCRIPTION
**Pull request by martinbigio**

### CODE REVIEW

**Comment by martinbigio** [comment]
cc @cpojer @davidaurelio

**Comment by davidaurelio** [comment]
Tests :-)
Do you want to accept `transformOptions`. They will get relevant soon :-)

**Comment by martinbigio** [comment]
> Do you want to accept transformOptions. They will get relevant soon :-)

How so? This is an utility function, it receives the resolutionResponse which should have already been generated based on transformed options :)

**Comment by davidaurelio** [comment]
Unfortunately, due to the way we currently generate modules, calling `module.getDependencies()` without the transform options used to produce the resolution response, the source of the module will be scanned again instead of using the cached version.

I know that this is clowny, but we need some reorganization in the lib to make that go away.

Feel free to put a `transformOptions` property on resolution responses with the options that were used to generate them.

**Comment by martinbigio** [comment]
@davidaurelio just updated this adding the `transformOptions` parameter and a test

**Comment by martinbigio** [comment]
tests were failing on master

**Comment by davidaurelio** [comment]
cherry-picked in 266f621e741a09d2a29dbe5c0900741e321ced7b

**Pull request closed without merging**
