### PR TITLE
Dedup dependencies on extractor

### PR DESCRIPTION
**Pull request by martinbigio**

### CODE REVIEW

**Comment by martinbigio** [comment]
cc @cpojer @davidaurelio

**Comment by cpojer** [comment]
Sounds good but can we instead just use a `Set` datastructure here and throughout where we need this? That way we don't need to keep track twice. (If yes, we probably need to bump version to 2.2 because it would be a minor breaking change :) ). An alternative is to just use an object, write to it the entire time and then do `Object.keys` at the end.

**Comment by martinbigio** [comment]
@cpojer don't we need to return the dependencies in the order they're defined for the getOrderedDependencies family functions? That's why I didn't use `Object.keys`.

**Comment by cpojer** [comment]
Set's iterate over their elements using insertion order (when you do for..of or use iterators directly).

**Comment by davidaurelio** [comment]
@martinbigio looks good to me. A `Set` would indeed be nicer. Feel free to do that in a follow up.

**Comment by davidaurelio** [comment]
On npm as v2.3.0

**Pull request merged**
