### PR TITLE
Support for absolute requires, and small fixes

### PR DESCRIPTION
**Pull request by davidaurelio**
This adds support for require calls with absolute paths and contains small bug-fixes (e.g. for single-character packages).

### CODE REVIEW

**Comment by davidaurelio** [comment]
cc @bestander

**Comment by bestander** [comment]
LGTM, should we wait for travis before shipping?

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Comment by bestander** [comment]
looks like you guys merge it manually :)

**Comment by davidaurelio** [comment]
lgtm :tongue:

**Pull request merged**
